# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('direct_link', models.URLField(max_length=500)),
                ('source_link', models.URLField(max_length=500)),
                ('rank', models.PositiveSmallIntegerField()),
                ('site', models.CharField(choices=[('g', 'Google'), ('y', 'Yandex'), ('i', 'Instagram')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=300)),
                ('scrapyd_response', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='results',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agregator.Tasks'),
        ),
    ]
