# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-29 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autobase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manufacturer',
            name='name',
        ),
        migrations.AddField(
            model_name='auto',
            name='name',
            field=models.CharField(default='Noname', max_length=50),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='brand',
            field=models.CharField(default='Noname', max_length=50, unique=True),
        ),
    ]
