# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 18:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autobase', '0002_auto_20160729_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('lastname', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Номер должен быть в формате 0хх 1234567 или 0хх 123-45-67', regex='0\\d{2,3}\\s?[0-9\\-]+')])),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autobase.Buyer')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AlterModelOptions(
            name='auto',
            options={'verbose_name': 'Автомобиль', 'verbose_name_plural': 'Автомобили'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'verbose_name': 'Производитель', 'verbose_name_plural': 'Производители'},
        ),
        migrations.AlterField(
            model_name='auto',
            name='body',
            field=models.CharField(choices=[('Passenger', (('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('limo', 'Limousine'), ('crossover', 'Crossover'), ('universal', 'Universal'), ('hatchback', 'Hatchback'), ('cabriole', 'Cabriole'), ('minivan', 'Minivan'), ('pickup', 'Pick-up'), ('offroad', 'Off-road'))), ('Lorry', (('trans', 'Car transporter'), ('tow', 'Tow truck'), ('log', 'Logging truck'), ('dump', 'Dump truck'), ('refrigerator', 'Refrigerator truck'))), ('Autobus', (('mini', 'Minibus'), ('city', 'City bus'), ('double', 'Double-decker')))], max_length=12),
        ),
        migrations.AlterField(
            model_name='auto',
            name='enginePower',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='auto',
            name='fuelType',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electric', 'Electric'), ('hibrid', 'Hibrid')], max_length=8),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autobase.Auto'),
        ),
        migrations.AddField(
            model_name='orders',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autobase.Auto'),
        ),
    ]
