# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-06 18:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autobase', '0003_auto_20160806_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autobase.Auto'),
        ),
    ]
